name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dokku deploy
        uses: actions/deploy@master
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          HOST: hack-the-flag.xyz
          PROJECT: locator
